config/routes.rb
Sharemycake::Application.routes.draw do
 
  get "celebrent/myevent" => "celebrent#myevent" , :as => "celebrent_myevent"
  get "celebrent/dash_board"=> "celebrent#dash_board" , :as => 'celebrent_dash_board'
  get "celebrent/create_event" => "celebrent#create_event" , :as=> 'celebrent_create_event'
  get "invitation/myevent"=>"invitation#myevent" , :as => 'invetation_my_event'
  get "invitation/dash_board" => "invitation#dash_board" ,:as => 'invitation_dash_board'
  get "invitation/create_event" => 'invitation#create_event' , :as => 'invitation_create_event'
  get "admin/payment"
  get "admin/event"
  get "admin/org"
  get "admin/dash_board" => "admin#dash_board" , :as => "admin"
  resources :events 
  post "events/choose_cause" => "events#choose_cause" , :as => "new_event_create"
   get "events/choose_org/:id" => "events#choose_org" , :as => "choose_org"
  post "events/email_template" => "events#email_template" , :as => "email_template"
  post "events/add_contact" => "events#add_contact" , :as => "add_contact"
  post "events/:id/index_page" => "events#index_page" , :as => "index_page"
  get "events/dash_board" => "events#dash_board" , :as => "dash_board_path"
  devise_for :users
  get "home/index"
  get "home/show"

   root 'home#index'

  

end

app/models/cause.rb
class Cause < ActiveRecord::Base
	has_many :orgs
	
end

app/models/event.rb
class Event < ActiveRecord::Base
	 has_many :organizations 
	 has_many :orgs , through: :organizations
	 belongs_to:user
	 #belongs_to :user, :class_name => "User", :foreign_key => "user_id"
	 #~ protected_attributes :
	 
	 def self.current_date(date,user)
		  today_date= Date.today
		  user.events.find(:all , :conditions =>['date<?',today_date])
	 end
end

app/models/mycontact.rb
class Mycontact < ActiveRecord::Base
	 #~ protected_attributes :user_attributes
	belongs_to:user
	accepts_nested_attributes_for :user
end

app/models/org.rb
class Org < ActiveRecord::Base
#belongs_to :event
has_many :organizations
has_many :events , through: :organizations
belongs_to :cause
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	belongs_to:event
	belongs_to:org
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # attr_accessible :password_confirmation, :email ,:password
  #~ protected_attributes :password_confirmation, :email ,:password
   has_many :events 
   has_many :mycontacts
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :autheraized 
  def payment
  end

  def event
  end

  def org
  end
  
  def dash_board
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  #~ #before_filter :
  def autheraized
    if user_signed_in? 
      if(current_user.admin == true)
          redirect_to admin_path
       
       elsif(((current_user.up_comming_event)&&(current_user.invitation)) ||  ((current_user.up_comming_event==false)&&(current_user.invitation)))
           redirect_to index_page_path
       
       elsif(((current_user.up_comming_event)&&(current_user.invitation==false)))
           
          redirect_to celebrent_dash_board_path
        else
          
          redirect_to  invitation_dash_board_path
        end
      end
      
    end
  def production
    unless(current_user.admin)
      redirect_to home_show_path
      end
  end
end

app/controllers/celebrent_controller.rb
class CelebrentController < ApplicationController
  def myevent
  end

  def dash_board
  p '#################################################'
  p @user=current_user
  p  @event=current_user.events.all
   @date=@event.first.id
  p  @upcoming_event=Event.current_date(@date,@user)
    
  end

  def create_event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  #~ before_action , only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index_page
   
     contact=current_user.mycontacts.build(event_params)
     if contact.save
     UserMailer.invitation(contact).deliver
     end
  end

  # GET /events/1
  # GET /events/1.json
  def choose_cause
    
  end
 
  def edit
   
  end
  def show
  end
  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def choose_org
   
    @cause=Cause.find_by_id(params[:id])
    
    p org=@cause.orgs.where(['orgs.status = ?', true]) # stores organizations name which are belongs to perticulare cause 
   
    p #event=$event
    e=current_user.evnets.first
    @org_event=e.organizations.create(org: org) # stores event_id and org_id 
   
    
 
  end

  # POST /events
  # POST /events.json
  def create
   
      @event =current_user.events.build(event_details) 
    #~ respond_to do |format|
      if @event.save
       $event=@event
        redirect_to new_event_create_path
    
      else
        render action: 'new'

    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
 
 def email_template
   @org_name=params[:org][:name]
   @org_share=params[:org][:share]
   
 end
 def add_contact
  
end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:email,:name,:phone_no)
    end
    
    def event_details
      params.require(:event).permit(:mobile_no, :title, :date, :description)  
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :autheraized , :only => :inedx
  def index
  end
  def show
  end
end

app/controllers/invitation_controller.rb
class InvitationController < ApplicationController
  def myevent
  end

  def dash_board
  end

  def create_event
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/celebrent_helper.rb
module CelebrentHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invitation_helper.rb
module InvitationHelper
end

app/views/admin/event.html.erb
<h1>Admin#event</h1>
<p>Find me in app/views/admin/event.html.erb</p>

app/views/admin/org.html.erb
<h1>Admin#org</h1>
<p>Find me in app/views/admin/org.html.erb</p>

app/views/admin/payment.html.erb
<h1>Admin#payment</h1>
<p>Find me in app/views/admin/payment.html.erb</p>

app/views/celebrent/create_event.html.erb
<h1>Celebrent#create_event</h1>
<p>Find me in app/views/celebrent/create_event.html.erb</p>

app/views/celebrent/myevent.html.erb
<h1>Celebrent#myevent</h1>
<p>Find me in app/views/celebrent/myevent.html.erb</p>

app/views/events/_form.html.erb
	<%= form_for(@event)  do |f| %>
		<% if @event.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

				<ul>
				<% @event.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
				</ul>
			</div>
		<% end %>

		<div class="field">
		
			<%#= f.label :user_id %><br>
			<%#= f.hidden :user_id %>
		</div>
		<div class="field">
	
			<%= f.label :mobile_no %><br>
			<%= f.text_field :mobile_no %>
			
		</div>
		<div class="field">
		
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</div>
		<div class="field">
			
			<%= f.label :date %><br>
			<%= f.date_select :date %>
			<%#= f. :date, :as => :datetime_picker %>

	<%#= f.input :closing_date, :as => :date_picker %>

	<%#= f.input :begin-at, :as => :time_picker %>
		</div>
		<div class="field">
			<%= f.label :description %><br>
			<%= f.text_area :description %>
		</div>
		<div class="actions">
		<p>
			<%= f.submit "contineu >>"%>
		</p></div>
	<% end %>

app/views/events/add_contact.html.erb
<%=form_for( :event ,url:index_page_path ) do |f| %>
<div>
<div>
<%=f.label :contant%>
 <%=f.text_area :message %>
</div>
<%=f.label :name %>
<%=f.text_field :name%>
</div>
<div>
<%=f.label :email %>
<%=f.text_field :email%>
</div>

<div>
<%=f.label :phone_number %>
<%=f.text_field :phone_no%>
</div>

<div>
<%=f.submit "invate" %>
</div>

<%end%>

app/views/events/choose_cause.html.erb
<div id="cause">
 <p>
 <%cause= Cause.find_by_name("education") %>
 <h4> <%=link_to "Education" , choose_org_path(:id=>cause.id)%></h4>
 
 <p>
</div>


<div id="cause">
<%cause= Cause.find_by_name("pollution") %>
 <h4><%=link_to "Pollution" ,choose_org_path(:id=>cause.id)%></h4>
</div>


<div id="cause">
<%cause= Cause.find_by_name("childern") %>
 <h4><%=link_to "Childern" , choose_org_path(:id=>cause.id)%></h4>
</div>


<div id="cause">
<%cause= Cause.find_by_name("social") %>
 <h4><%=link_to "Social" , choose_org_path(:id=>cause.id)%></h4>
</div>

app/views/events/choose_org.html.erb
<%= form_for( :org ,url:email_template_path ) do |f|%> 
<% @org.each do |o| %>
<div  >
 <%= f.radio_button "name" , o.name  %>
 <%=o.name%>
 </div>
 
 
 
<%end%>
 <div>
 <%=f.label :share %>
 <input type="text" name ="share" >
 </div>
<div >
 
  <%=f.submit "continue >>"%>
  </div>
<%end%>

	

app/views/events/edit.html.erb
<%= form_for( :org ,url:email_template_path ) do |f|%> 
<% @org.each do |o| %>
<div  >
 <%= f.radio_button "name" , o.name  %>
 <%=o.name%>
 </div>
 
 
 
<%end%>
 <div>
 <%=f.label :share %>
 <input type="text" name ="share" >
 </div>
<div >
 
  <%=f.submit "continue >>"%>
  </div>
<%end%>

	

app/views/events/email_template.html.erb
<%=form_for( :template ,url:add_contact_path ) do |f| %>
<div>
  <ul>
	  <li>
		   <a></a>
			 <a><%= image_tag(image_url 'org3.jpg' ,:size =>"85x85")  %></a>
			 <%= f.radio_button "id" ,1   %>
		</li>
		<li>
		   <a></a>
			 <a><%= image_tag(image_url 'org3.jpg' )  %></a>
			 <%= f.radio_button "id" ,2   %>
		</li>
		<li>
		   <a></a>
			 <a><%= image_tag(image_url 'org3.jpg' )  %></a>
			 <%= f.radio_button "id" ,3   %>
		</li>
	 </ul>
</div>
<div>
  <%=f.submit "contineu >>" %>
</div>
<%end%>

app/views/events/new.html.erb
<div class="body">
		<div>
			<div class="featured">
				 <%#= image_tag(image_url 'camping.jpg' )  %>
				
				
			</div>
			<div>
				<div>
					<div>
				
						<div class="section">
						   <%= render 'form' %>
							<p>
								
							</p>
							<ul>
								<li>
									<p>
										
									</p>
								</li>
								<li>
									<p>
										
									</p>
								</li>
								<li>
									<p>
										
									</p>
								</li>
								<li>
									<p>
										
									</p>
								</li>
							</ul>
							<ul class="last">
								<li>
									<p>
										
								</li>
								<li>
									<p>
									
									</p>
								</li>
								<li>
									<p>
									
									</p>
								</li>
								<li>
									<p>
									
									</p>
								</li>
							</ul>
						</div>
						<div>
							<h3>My Contribution</h3>
							<ul>
								<li>
									<div>
										 <%#= image_tag(image_url "org1.jpg", :size => "85x85") %>
										
									</div>
								</li>
								<li>
									<div>
										<%#= image_tag(image_url 'org2.gif' , :size => "85x85") %>
										<p>
											your contribution is so for ..............
										</p>
									</div>
								</li>
								<li class="last">
									<div>
										<%#= image_tag(image_url 'org3.jpg' , :size => "85x85") %>
										
									</div>
								</li>
							</ul>
								<a ><%#=link_to "View All", home_index_path%></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/events/show.html.erb
<div id="cause">
 <p>
 <%cause= Cause.find_by_name("education") %>
 <h4> <%=link_to "Education" , choose_org_path(:id=>cause.id)%></h4>
 
 <p>
</div>


<div id="cause">
<%cause= Cause.find_by_name("pollution") %>
 <h4><%=link_to "Pollution" ,choose_org_path(:id=>cause.id)%></h4>
</div>


<div id="cause">
<%cause= Cause.find_by_name("childern") %>
 <h4><%=link_to "Childern" , choose_org_path(:id=>cause.id)%></h4>
</div>


<div id="cause">
<%cause= Cause.find_by_name("social") %>
 <h4><%=link_to "Social" , choose_org_path(:id=>cause.id)%></h4>
</div>

app/views/events/show.js.erb
#$("#sortable").html("<%= escape_javascript(render :partial => '/categories/sortify', :object => @sortify, :locals => {:sort_params => @sort_params}) %>");

app/views/home/index.html.erb
<div class="body">
		<div>
			<div class="featured">
				 <%= image_tag(image_url 'camping.jpg' )  %>
				
				<div>
					<div>
						<h3><span>C</span>reate <span>A</span> <span>E</span>vent <span>T</span>ODAY!</h3>
						<p>
							create a invitation with some cause to your friends and collect gift from your friends then share some ammount to the organizaton
						</p>
							
					</div>
				</div>
			</div>
			<div>
				<div>
					<div>
				
						<div class="section">
							<h2>How to create a event?</h2>
							<p>
								
							</p>
							<ul>
								<li>
									<p>
										click the create event 
									</p>
								</li>
								<li>
									<p>
										enter your event name , date ,venu and discribtion 
									</p>
								</li>
								<li>
									<p>
										then select the cause , organization and share ammount
									</p>
								</li>
								<li>
									<p>
										select the email template for your invitation 
									</p>
								</li>
							</ul>
							<ul class="last">
								<li>
									<p>
										add your friends list and send them the invetation 
									</p>
								</li>
								<li>
									<p>
									
									</p>
								</li>
								<li>
									<p>
									
									</p>
								</li>
								<li>
									<p>
									
									</p>
								</li>
							</ul>
						</div>
						<div>
							<h3>List of organization</h3>
							<ul>
								<li>
									<div>
										 <%= image_tag(image_url "org1.jpg", :size => "85x85") %>
										<p>
											The motivation of this organization, is to help the childerns who are unable to continue there education .
										</p>
									</div>
								</li>
								<li>
									<div>
										<%= image_tag(image_url 'org2.gif' , :size => "85x85") %>
										<p>
											The motivation of this organization, to pollution free environment.
										</p>
									</div>
								</li>
								<li class="last">
									<div>
										<%= image_tag(image_url 'org3.jpg' , :size => "85x85") %>
										<p>
											The motivation of this organization,.
										</p>
									</div>
								</li>
							</ul>
								<a ><%=link_to "View All", home_index_path%></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	

app/views/invitation/create_event.html.erb
<h1>Invitation#create_event</h1>
<p>Find me in app/views/invitation/create_event.html.erb</p>

app/views/invitation/dash_board.html.erb
<h1>Invitation#dash_board</h1>
<p>Find me in app/views/invitation/dash_board.html.erb</p>

app/views/invitation/myevent.html.erb
<h1>Invitation#myevent</h1>
<p>Find me in app/views/invitation/myevent.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta charset="UTF-8">
	<title>Sharemycake</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="header">
		<div>
			
			
			<a  id="logo" href="www.google.com"> <%= image_tag(image_url 'logo.png') %></a>
			<ul>
				<li class="selected">
					<a ><%=link_to "home" , home_index_path%> </a>
				</li>
				<li>
					<a ><%=link_to "About", home_show_path%></a>
				</li>
				<li>
					<a ><%=link_to "organization", home_index_path%></a>
				</li>
				<li>
					<a ><%=link_to "create event", new_event_path%></a>
				</li>
				
			</ul>
			<div>
				<p>
					<%=link_to "login",home_index_path%><%= "       " %><%=link_to "register" , home_index_path %> 
				</p>
			</div>
		</div>
	</div>
	<%=yield%>
	<%=link_to "logout ", destroy_user_session_path , method: :delete %>
	<div class="footer">
		<div>
			<div>
				
				<p>
					
				</p>
				<!--<form action="index.ht">
					<input type="text" value="Email Address" onblur="this.value=!this.value?'Email Address':this.value;" onfocus="this.select()" onclick="this.value='';">
					<input type="submit" value="Get">
				</form>
			</div>
			<div><!--
				<h4>LATEST BLOG</h4>
				<ul>
					<li>
						<p>
							<a href="blog.html">Phasellus parea ut di tincidunt blandit nisi ut pellentesque.</a>
						</p>
						<span>11/07/2011</span>
					</li>
					<li>
						<p>
							<a href="blog.html">Donec dictum semper augue, ut consectetur magna posuere eget.</a>
						</p>
						<span>11/03/2011</span>
					</li>
					<li>
						<p>
							<a href="blog.html">Cum sociis natoque penatibus et magnis dis parturient.</a>
						</p>
						<span>11/27/2011</span>
					</li>
				</ul>
			</div>-->
			<div class="connect">
			
				<h4>FOLLOW US:</h4>
				<a href="http://freewebsitetemplates.com/go/facebook/" class="facebook">Facebook</a> <a href="http://freewebsitetemplates.com/go/twitter/" class="twitter">Twitter</a> <a href="http://freewebsitetemplates.com/go/googleplus/" class="google">Google+</a>
			</div>
		</div>
		<div>
			<p>
				Summer Camp &#169; 2011 | All Rights Reserved
			</p>
		</div>
	</div>

</body>
</html>